config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :infors
    resources :categories
    resources :questions
    resources :options
    resources :users
    resources :submissions
    resources :judges
    resources :tokens
    resources :token_judges
    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "users/registrations" , omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions , only: [:show] do
    resources :submissions
    resources :options
  end
  resources :categories
  resources :infors
  resources :tokens , only: [:index]
  post 'token', to: "tokens#result", as: :result

  get '/about', to: "static_pages#about", as: :static_about
  get '/play', to: "static_pages#play",  as: :static_play

  get 'rank/index'

  root "infors#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/infor.rb
class Infor < ApplicationRecord
end

app/models/judge.rb
class Judge < ApplicationRecord
  belongs_to :question, foreign_key: :question_id
  belongs_to :user, foreign_key: :user_id

  def update(state_code)
    self.state = state_code
    self.save
  end

  def ever_solve_problem?
    self.state == 1
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question, foreign_key: :question_id
end

app/models/question.rb
class Question < ApplicationRecord
  mount_uploader :image, QuestionImageUploader
  validates :title, presence: :true
  validates :answer, presence: :true
  validates :rewardpoint, presence: :true
  validates :punishpoint, presence: :true

  has_many :submissions, dependent: :destroy
  has_many :judges, dependent: :destroy
  has_many :options, dependent: :destroy
  belongs_to :category, foreign_key: :category_id

  def correct?(solution)
    solution == answer
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :question, foreign_key: :question_id
  belongs_to :user, foreign_key: :user_id
end

app/models/token.rb
class Token < ApplicationRecord
  has_many :judge_tokens, dependent: :destroy
end

app/models/token_judge.rb
class TokenJudge < ApplicationRecord
  belongs_to :token, foreign_key: :token_id
  belongs_to :user, foreign_key: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :submissions, dependent: :destroy
  has_many :judges, dependent: :destroy
  has_many :token_judges, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.remote_avatar_url = auth.info.image
    end
  end

  def give_reward(reward)
    self.score += reward
    if self.score < 0
      self.score = 0
    end
    self.save
  end
  
  def give_punish(punish)
    @answerby = Judge.find_by_id(self.id)
    self.score += punish
    if self.score < 0
      self.score = 0
    end
    self.save
  end

  def count_rank
    users = User.order(:score => :desc, :name => :asc)
    users.each_with_index do |u, i|
      if u.name == self.name or u.email == self.email
        return (i+1)
      end
    end
  end

  def email_required?
    false
  end
end

app/controllers/infors_controller.rb
class InforsController < ApplicationController
  def index
    @infors = Infor.order("updated_at DESC").limit(30)
  end
end

app/controllers/rank_controller.rb
class RankController < ApplicationController
  def index
    @users = User.order("score DESC", "updated_at ASC").limit(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_hi_user
    if flash[:notice] == "Successfully authenticated from Facebook account." && user_signed_in? 
      return link_to("Hi! #{current_user.name}", edit_user_registration_path, class: "pure-menu-link")
    end
  end

  def render_question(q)
    return link_to(q.title, question_path(q))
  end

  def render_answer(submission)
    if submission.state == "AC"
      return content_tag(:font, "Accepted", class: "AC" )
    elsif submission.state == "WA"
      return content_tag(:font, "Wrong Answer", class: "WA" )
    elsif submission.state == "answered"
      return content_tag(:font, "Resubmitted" )
    end
  end

  def render_point_get(submission, q)
    if submission.state == "AC"
      return q.rewardpoint
    elsif submission.state == "WA"
      return q.punishpoint
    else
      return 0
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/infors_helper.rb
module InforsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def new_or_not(question)
    return ((Time.current -  question.updated_at)/86400).to_i
  end
  def question_check_mark(question)
    if user_signed_in? && Judge.exists?(["question_id = ? AND user_id = ? AND state = ?", question.id, current_user.id, 1])
      return image_tag("check.png", id: "check")
    elsif user_signed_in? && Judge.exists?(["question_id = ? AND user_id = ? AND state = ?", question.id, current_user.id, 2])
      return image_tag("cancel.png", id: "cancel")
    else
      return image_tag("cursor.png", id: "cursor")
    end
  end
end

app/helpers/rank_helper.rb
module RankHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/fields/question_image_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/question_image_field/_index.html.erb
<%= image_tag field.thumb %>

app/views/fields/question_image_field/_show.html.erb
<%= image_tag field.small %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    Copyright © 2017 台大資訊工程學系 - 資訊之夜學術部<br> 
     主辦單位保留修改、終止、變更活動內容細節之權利
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSIENight</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div id="layout">
      <!-- Menu toggle -->
      <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
      </a>

      <div id="menu">
        <div class="pure-menu">
          <%= link_to "Latest News", root_path, :class => "pure-menu-heading" %>

          <ul class="pure-menu-list">
            <li class="pure-menu-item"><%= link_to "Home", root_path, class: "pure-menu-link" %></li>
            
            <li class="pure-menu-item"><%= link_to "How to Play" , static_play_path, :class => "pure-menu-link" %></li>
            
            <li class="pure-menu-item"><%= link_to "Problem Set", categories_path, :class => "pure-menu-link" %></li>

            <li class="pure-menu-item"><%= link_to "Rank",rank_index_path, :class => "pure-menu-link" %></li>
            
            <li class="pure-menu-item"><%= link_to "About Us" , static_about_path, :class => "pure-menu-link" %></li>
            <li></li>
          </ul>
        </div>
        <div class="pure-menu">
          <%= link_to "Account", root_path, :class => "pure-menu-heading" %>
          <ul class="pure-menu-list">
            <%= render 'infors/user' %>
          </ul>
        </div>

      </div>
      <%= yield %>
    </div>
    <script src="/js/ui.js" type="text/javascript"></script>
  </body>
</html>